[package]
name = "voxl-instruction-set"
version = "0.2.0"
authors = ["aidos9 <20310468+aidos9@users.noreply.github.com>"]
edition = "2018"

[build-dependencies]
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }